services:
  pubsub:
    image: redis
    container_name: pubsub
    hostname: pubsub
    ports:
      - 6380:6380
    volumes:
      - ./pubsub/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - likeminds-network
  
  pandemonium:
    container_name: pandemonium
    hostname: pandemonium
    build:
      dockerfile: ./Dockerfile.pandemonium
    ports:
      - 8081:8081
    environment:
      - REDIS_DSN=pubsub:6380
      - POSTGRES_HOST=caravan_postgres
      - CARAVAN_BASE_URL=http://caravan:8000
      - SWARM_BASE_URL=http://swarm:8081
    restart: unless-stopped
    networks:
      - likeminds-network
    depends_on:
      - pubsub

networks:
  likeminds-network:
    external: true
